# Generated by Django 5.1.4 on 2025-01-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_system', '0002_account_delete_choice_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drivername', models.CharField(max_length=200)),
                ('car_type', models.CharField(max_length=200)),
                ('plate_number', models.CharField(max_length=200)),
                ('capacity', models.IntegerField()),
                ('special', models.CharField(max_length=200)),
            ],
        ),
    ]
