# Generated by Django 5.1.4 on 2025-01-27 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_system', '0003_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='username',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
