# Generated by Django 5.1.4 on 2025-01-27 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_system', '0006_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ride_system.driver'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='shareSet',
            field=models.ManyToManyField(blank=True, to='ride_system.account'),
        ),
    ]
