# Generated by Django 5.1.4 on 2025-01-27 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride_system', '0007_alter_trip_driver_alter_trip_shareset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='time',
        ),
    ]
